export const demoDensityActionTypes = {
    DENSITY_DATA_START : 'DENSITY_DATA_START',
    DENSITY_DATA_SUCCESS: 'DENSITY_DATA_SUCCESS',
    DENSITY_DATA_FAILURE : 'DENSITY_DATA_FAILURE',

    DENSITY_OPTIONS_START: 'DENSITY_OPTIONS_START',
    DENSITY_OPTIONS_SUCCESS: 'DENSITY_OPTIONS_SUCCESS',
    DENSITY_OPTIONS_FAILURE: 'DENSITY_OPTIONS_FAILURE'
}