export const demoDensityActionTypes = {
    DENSITY_OPTIONS_START: 'DENSITY_OPTIONS_START',
    DENSITY_OPTIONS_SUCCESS: 'DENSITY_OPTIONS_SUCCESS',
    DENSITY_OPTIONS_FAILURE: 'DENSITY_OPTIONS_FAILURE'
}