export const demoDensityActionTypes = {
    GET_DATA_START : 'GET_DATA_START',
    GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
    GET_DATA_FAILURE : 'GET_DATA_FAILURE',

    GET_OPTIONS_START: 'GET_OPTIONS_START',
    GET_OPTIONS_SUCCESS: 'GET_OPTIONS_SUCCESS',
    GET_OPTIONS_FAILURE: 'GET_OPTIONS_FAILURE'
}